Repository rustic-rs/rustic, pull requests merged in 2023-08, with the labels that each got.

#785 handle non-unicode link-targets
  changelog/new.txt
  crates/rustic_core/src/backend/ignore.rs
  crates/rustic_core/src/backend/local.rs
  crates/rustic_core/src/backend/node.rs
  crates/rustic_core/src/commands/restore.rs
  crates/rustic_core/src/error.rs
  src/commands/diff.rs
  src/commands/ls.rs
Labels: C-bug, A-compatibility, O-unix

#762 docs: Add `CONTRIBUTING.md`
  CONTRIBUTING.md
  README.md
  docs/dev/development_guide.md
Labels: A-docs, A-meta

#766 docs: Fully document configuration specification and environment variables
  config/README.md
Labels: A-docs, C-enhancement, A-examples, S-waiting-for-review

#830 ci: Lint markdown with dprint, run initial dprint fmt
  .cargo/config.toml
  .github/workflows/lint-markdown-toml.yaml
  CONTRIBUTING.md
  Cargo.toml
  README.md
  config/README.md
  config/copy_example.toml
  config/full.toml
  config/local.toml
  config/ovh-hot-cold.toml
  config/par2.toml
  config/rustic.toml
  crates/rustic_core/Cargo.toml
  crates/rustic_core/README.md
  crates/rustic_core/src/cdc/README.md
  crates/rustic_testing/Cargo.toml
  docs/FAQ.md
  docs/comparison-restic.md
  dprint.json
  xtask/Cargo.toml
Labels: A-docs, C-enhancement, A-ci, A-ui-ux, S-waiting-for-review

#822 refactor: Add metadata to crate manifests
  Cargo.toml
  crates/rustic_core/Cargo.toml
Labels: C-enhancement, A-meta, A-packaging, S-waiting-for-review

#829 chore: add support for `cargo-binstall`
  Cargo.toml
Labels: C-enhancement, A-meta, A-packaging, S-waiting-for-review
