Repository rustic-rs/rustic, pull requests merged in 2024-10, with the labels that each got.

#1280 fix(docs): update configuration documentation to align with recent changes
  config/README.md
Labels: A-docs, S-waiting-for-review

#1276 feat(commands): add a `docs` command to easily access the user, dev and config documentation
  Cargo.lock
  Cargo.toml
  src/application.rs
  src/commands.rs
  src/commands/docs.rs
Labels: A-docs, C-enhancement, A-commands, A-ui-ux, S-waiting-for-review

#1282 fix(deps): update rustic_core and other dependencies and fix merge precedence
  Cargo.lock
  Cargo.toml
  src/commands/backup.rs
  src/commands/copy.rs
  src/commands/forget.rs
  src/commands/key.rs
  src/commands/tui/restore.rs
  src/commands/webdav.rs
  src/config.rs
  src/config/progress_options.rs
  src/filtering.rs
Labels: C-refactor, A-core, S-waiting-for-review, A-dependencies

#1277 fix(docs/cli): improve the descriptions of the CLI commands
  src/commands.rs
Labels: C-enhancement, A-cli, A-ui-ux, S-waiting-for-review

#1230 feat(check): Allow to only check trees+packs for given snapshots
  src/commands/check.rs
Labels: C-enhancement, A-commands

#1287 ci: add triage label to new issues only if no label has been set when creating it
  .github/workflows/triage.yml
Labels: C-bug, A-ci

#1289 chore(deps): upgrade dependencies
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#1293 ci: add missing feature self-update to tests and checks
  .github/workflows/ci.yml
  .github/workflows/cross-ci.yml
Labels: C-bug, A-ci

#1308 chore: add Zlib to allowed licenses in deny.toml
  deny.toml
Labels: A-ci

#1309 chore(deps): update rustic_core
  Cargo.lock
  Cargo.toml
  src/commands/prune.rs
Labels: A-dependencies

#1311 docs: add status badge for docker image build and shorten workflow name
  .github/workflows/release-image.yml
  README.md
Labels: A-docs, C-enhancement, A-ci

#1314 fix(deps): update rustic_core to version 0.5.3
  Cargo.lock
  Cargo.toml
Labels: C-bug, A-core, P-high, A-dependencies

#1307 build: introduce a new feature 'release' that includes the 'self-update' feature
  .github/workflows/ci.yml
  .github/workflows/cross-ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release-cd.yml
  Cargo.toml
Labels: C-enhancement, A-ci, A-packaging, S-waiting-for-review, A-build

#1323 fix(deps): downgrade self-update to fix problems finding right target
  Cargo.lock
  Cargo.toml
Labels: C-bug, S-waiting-for-review, A-dependencies

#1330 chore(deps): update abscissa framework
  Cargo.lock
  Cargo.toml
  src/application.rs
Labels: A-dependencies
