Repository rustic-rs/rustic, pull requests merged in 2024-09, with the labels that each got.

#1139 chore: Remove self-update from default crate features
  Cargo.toml
Labels: C-enhancement, A-packaging, A-build

#1240 fix(config)!: use multiple options only as array in config profile
  Cargo.lock
  Cargo.toml
  config/full-one.toml
  config/full.toml
  config/local.toml
  config/rustic.toml
  config/services/rclone_ovh-hot-cold.toml
  src/commands.rs
  src/commands/backup.rs
  src/commands/key.rs
  src/config.rs
  src/filtering.rs
  tests/show-config-fixtures/empty.txt
Labels: A-config

#1069 perf: Reduce memory usage of restore
  src/commands/restore.rs
Labels: C-enhancement, perf
